-- Re-insert Spanish cities (idempotent)
INSERT INTO public.cities (name) VALUES
  ('Madrid'),
  ('Barcelona'),
  ('Valencia'),
  ('Sevilla'),
  ('Zaragoza'),
  ('Málaga'),
  ('Murcia'),
  ('Palma de Mallorca'),
  ('Las Palmas de Gran Canaria'),
  ('Bilbao'),
  ('Alicante'),
  ('Córdoba'),
  ('Valladolid'),
  ('Vigo'),
  ('Gijón'),
  ('Hospitalet de Llobregat'),
  ('A Coruña'),
  ('Vitoria-Gasteiz'),
  ('Granada'),
  ('Elche'),
  ('Oviedo'),
  ('Santa Cruz de Tenerife'),
  ('Badalona'),
  ('Cartagena'),
  ('Terrassa'),
  ('Jerez de la Frontera'),
  ('Sabadell'),
  ('Móstoles'),
  ('Alcalá de Henares'),
  ('Pamplona'),
  ('Fuenlabrada'),
  ('Almería'),
  ('Leganés'),
  ('Donostia-San Sebastián'),
  ('Burgos'),
  ('Santander'),
  ('Castellón de la Plana'),
  ('Getafe'),
  ('Albacete'),
  ('Alcorcón')
ON CONFLICT (name) DO NOTHING;