// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vnbsaoaxdksbgybtrzwn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZuYnNhb2F4ZGtzYmd5YnRyenduIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU2MDU4NzcsImV4cCI6MjA3MTE4MTg3N30.WgNa82zd5_UD8GiBxxwje2ls64A6H_db8076imkkLUE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});